# Author Info
Name: **Ejaz-ur-Rehman**\
Business Unit Head | Data Analyst\
MBA (Accounting & Finance), MS (Finance)\
Crystal Tech (Project of MUZHAB Group)\
Karachi, Pakistan

![Date](https://img.shields.io/badge/Date-25--Aug--2025-green?logo=google-calendar)
[![Email](https://img.shields.io/badge/Email-ijazfinance%40gmail.com-blue?logo=gmail)](mailto:ijazfinance@gmail.com)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Ejaz--ur--Rehman-blue?logo=linkedin)](https://www.linkedin.com/in/ejaz-ur-rehman/)
[![GitHub](https://img.shields.io/badge/GitHub-ejazurrehman-black?logo=github)](https://github.com/ejazurrehman)

# Numpy
-------
In Python, NumPy (short for Numerical Python) is a powerful open-source library used for numerical computing. It provides support for working with large, multi-dimensional arrays and matrices, along with a collection of high-performance mathematical functions to operate on these arrays.

## Key Features of NumPy:
### 1. N-Dimensional Array Object (ndarray):
 - Core of NumPy is the ndarray, a fast, flexible, and efficient container for large datasets.
 - Much faster than Python’s built-in lists when performing mathematical operations.
### 2. Mathematical Operations:
 - Provides built-in functions for linear algebra, statistics, Fourier analysis, random number generation, etc.
### 3. Vectorization:
 - Allows operations on entire arrays without writing explicit loops (making code cleaner and faster).
### 4. Integration:
 - Works well with other libraries like Pandas, Matplotlib, Scikit-learn, and more.

In [2]:
# import numpy as np
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Perform basic operations
print("Array:", arr)
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))

Array: [1 2 3 4 5]
Mean: 3.0
Sum: 15


## What is array in numpy?
------------------------------------------------------------------------------------------------------------------------------------------
In NumPy, an array is a special data structure called an ndarray (N-dimensional array). It is the core object of NumPy and is used to store collections of elements (numbers, strings, or other data types) in a grid-like structure with fixed size and data type.

### Characteristics of a NumPy Array:
### 1. Homogeneous:
- All elements in a NumPy array must be of the same data type (e.g., all integers, all floats).
### 2. N-Dimensional:
- Arrays can be 1D (vector), 2D (matrix), or higher dimensions (tensor).
### 3. Indexable & Slicable:
- You can access and slice data just like Python lists, but with more powerful features.
### 4. Efficient & Fast:
- Stored in continuous memory blocks, making operations faster than Python lists.
### 5. Supports Vectorized Operations:
- You can perform element-wise arithmetic without loops.

### Example: Creating Arrays in NumPy:

In [3]:
import numpy as np

# 1D Array (like a list)
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# 2D Array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)

# 3D Array (tensor)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", arr3)


1D Array: [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### NOTE: 
- A NumPy array is a multi-dimensional, homogeneous data structure that is more efficient and powerful than Python lists for numerical computations.

## Usage of 1D, 2D and 3D arrays in Numpy
-----------------------------------------------------------------------------------------------------------------------------------------------
NumPy arrays can be 1D, 2D, or 3D (and higher), and each has its own use cases depending on the type of data we are working with.
### 1D Array (Vector):
- What it is: A simple list-like structure, one row of elements.
- Use case: Useful for linear data such as sequences, signals, feature vectors in machine learning, or storing simple datasets.
- Use case examples:
  - Student marks list [85, 90, 78, 92]
  - Prices of products [100, 200, 150]
  - ML input features for one observation [height, weight, age]
### 2D Array (Matrix):
- What it is: Data arranged in rows and columns (like a table).
- Use case: Used for matrices in linear algebra, images (grayscale), or datasets where you have rows = observations and columns = features.
- Use case examples:
  - Student marks table
### 3D Array (Tensor):
- What it is: Data arranged in multiple 2D matrices stacked together (like a cube).
- Use case: Used in scientific computing, image processing (RGB images), video frames, deep learning (tensors).
- Use case examples:
  - RGB Images → shape (height, width, 3)
  - Videos → shape (frames, height, width, channels)
  - Deep Learning → input data tensors (batch_size, features, time_steps)
### Summary:
- 1D Array: Linear data → vectors, lists, sequences.
- 2D Array: Tabular/matrix data → datasets, images, matrices.
- 3D Array: Multi-layer data → images (RGB), videos, tensors for ML/DL.



In [4]:
# creating numpy arrays
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [5]:
print("1D Array:", a)
print("2D Array:\n", b)
print("3D Array:\n", c)


1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
a.shape


(3,)

### Interpretation:
- This means the array has 1 dimension (it’s a 1D array).
- That single dimension has 3 elements.
- The comma ( , ) indicates it is a tuple describing dimensions.
- So (3,) = "One row with 3 elements" (like a vector).

In [8]:
b.shape

(2, 3)

### Interpretation:
- 2 → Number of rows
- 3 → Number of columns
- Total elements = 2 × 3 = 6

In [9]:
c.shape

(2, 2, 2)

### Interpretation:
- 3D array
- 2 matrices
- Each matrix has 2 rows and 2 columns
- Total elements = 2 × 2 × 2 = 8

In [10]:
# initializing arrays
zero_array = np.zeros((3, 4))
print("Zero Array:\n", zero_array)

one_array = np.ones((2, 3))
print("\nOne Array:\n", one_array)

full_array = np.full((2, 2), 7)
print("\nFull Array:\n", full_array)


Zero Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

One Array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full Array:
 [[7 7]
 [7 7]]


In [12]:
# check the data type of arrays
print("Data type of a:", a.dtype)
print("Data type of b:", b.dtype)
print("Data type of c:", c.dtype)


Data type of a: int64
Data type of b: int64
Data type of c: int64


In [11]:
# creating an identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix:\n", identity_matrix)



Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# check data type of identity matrix
print("Data type of identity_matrix:", identity_matrix.dtype)


Data type of identity_matrix: float64


In [14]:
# check the type of arrays
print("Type of a:", type(a))
print("Type of b:", type(b))
print("Type of c:", type(c))
print("Type of zero_array:", type(zero_array))
print("Type of one_array:", type(one_array))
print("Type of full_array:", type(full_array))
print("Type of identity_matrix:", type(identity_matrix))


Type of a: <class 'numpy.ndarray'>
Type of b: <class 'numpy.ndarray'>
Type of c: <class 'numpy.ndarray'>
Type of zero_array: <class 'numpy.ndarray'>
Type of one_array: <class 'numpy.ndarray'>
Type of full_array: <class 'numpy.ndarray'>
Type of identity_matrix: <class 'numpy.ndarray'>


In [36]:
# Create an empty array with 2 elements
np.empty(2) 

array([6.95195932e-310, 9.47341672e-312])

In [37]:
np.arange(4)

array([0, 1, 2, 3])

- And even an array that contains a range of evenly spaced intervals. To do this, we will specify the first number, last number, and the step size.

In [ ]:
np.arange(2, 9, 2) # Create an array with values from 2 to 8 (exclusive) with a step of 2

array([2, 4, 6, 8])

In [40]:
# create an array with values from 2 to 23 with a step of 3
np.arange(2, 24, 3)

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [ ]:
np.linspace(0, 10, num=5) # Create an array of 5 equally spaced values between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

- While the default data type is floating point (np.float64), we can explicitly specify which data type you want using the dtype keyword.

In [ ]:
x = np.ones(2, dtype=np.int64) # Create an array of ones with 2 elements
x

array([1, 1])

## Array attributes

---

In [19]:
# check the shape of arrays
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c:", c.shape)
print("Shape of zero_array:", zero_array.shape)
print("Shape of one_array:", one_array.shape)
print("Shape of full_array:", full_array.shape)
print("Shape of identity_matrix:", identity_matrix.shape)


Shape of a: (3,)
Shape of b: (2, 3)
Shape of c: (2, 2, 2)
Shape of zero_array: (3, 4)
Shape of one_array: (2, 3)
Shape of full_array: (2, 2)
Shape of identity_matrix: (3, 3)


In [22]:
# check the length of arrays
print("Length of a:", len(a))
print("Length of b:", len(b))
print("Length of c:", len(c))
print("Length of zero_array:", len(zero_array))
print("Length of one_array:", len(one_array))
print("Length of full_array:", len(full_array))
print("Length of identity_matrix:", len(identity_matrix))


Length of a: 3
Length of b: 2
Length of c: 2
Length of zero_array: 3
Length of one_array: 2
Length of full_array: 2
Length of identity_matrix: 3


In [21]:
# check the number of dimensions of arrays
print("Number of dimensions of a:", a.ndim)
print("Number of dimensions of b:", b.ndim)
print("Number of dimensions of c:", c.ndim)
print("Number of dimensions of zero_array:", zero_array.ndim)
print("Number of dimensions of one_array:", one_array.ndim)
print("Number of dimensions of full_array:", full_array.ndim)
print("Number of dimensions of identity_matrix:", identity_matrix.ndim)


Number of dimensions of a: 1
Number of dimensions of b: 2
Number of dimensions of c: 3
Number of dimensions of zero_array: 2
Number of dimensions of one_array: 2
Number of dimensions of full_array: 2
Number of dimensions of identity_matrix: 2


In [ ]:
# check the size of arrays- total elements
print("Size of a:", a.size)
print("Size of b:", b.size)
print("Size of c:", c.size)
print("Size of zero_array:", zero_array.size)
print("Size of one_array:", one_array.size)
print("Size of full_array:", full_array.size)
print("Size of identity_matrix:", identity_matrix.size)


Size of a: 3
Size of b: 6
Size of c: 8
Size of zero_array: 12
Size of one_array: 6
Size of full_array: 4
Size of identity_matrix: 9


## Basic operations in arrays

---

In [25]:
a

array([1, 2, 3])

In [26]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# adding arrays
g = a + b
g

array([[2, 4, 6],
       [5, 7, 9]])

In [27]:
h1 = np.add (a, b)
h1

array([[2, 4, 6],
       [5, 7, 9]])

In [28]:
# subtracting arrays
i1 = np.subtract(a, b)
i1

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [29]:
k = a - b
k

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [30]:
# multiplying arrays
j1 = np.multiply(a, b)
j1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [31]:
m = a * b
m

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [32]:
# dividing arrays
k1 = np.divide(a, b)
k1

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [33]:
n = a / b
n

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [34]:
# squaring elements of a array
l1 = np.square(a)
l1

array([1, 4, 9])

In [35]:
j = a**2
j

array([1, 4, 9])

In [42]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

## sorting arrays
---

In [ ]:
np.sort(arr) # Sort the array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.concatenate((a, b)) # Concatenate two arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
np.concatenate((x, y), axis=0) # Concatenate along the first axis (rows)

array([[1, 2],
       [3, 4],
       [5, 6]])