# Author Info
Name: **Ejaz-ur-Rehman**\
Business Unit Head | Data Analyst\
MBA (Accounting & Finance), MS (Finance)\
Crystal Tech (Project of MUZHAB Group)\
Karachi, Pakistan

![Date](https://img.shields.io/badge/Date-25--Aug--2025-green?logo=google-calendar)
[![Email](https://img.shields.io/badge/Email-ijazfinance%40gmail.com-blue?logo=gmail)](mailto:ijazfinance@gmail.com)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Ejaz--ur--Rehman-blue?logo=linkedin)](https://www.linkedin.com/in/ejaz-ur-rehman/)
[![GitHub](https://img.shields.io/badge/GitHub-ejazurrehman-black?logo=github)](https://github.com/ejazurrehman)

# Numpy

In Python, NumPy (short for Numerical Python) is a powerful open-source library used for numerical computing. It provides support for working with large, multi-dimensional arrays and matrices, along with a collection of high-performance mathematical functions to operate on these arrays.

## Key Features of NumPy:

### 1. N-Dimensional Array Object (ndarray):
 - Core of NumPy is the ndarray, a fast, flexible, and efficient container for large datasets.
 - Much faster than Python’s built-in lists when performing mathematical operations.

### 2. Mathematical Operations:
 - Provides built-in functions for linear algebra, statistics, Fourier analysis, random number generation, etc.

### 3. Vectorization:
 - Allows operations on entire arrays without writing explicit loops (making code cleaner and faster).

### 4. Integration:
 - Works well with other libraries like Pandas, Matplotlib, Scikit-learn, and more.

In [2]:
# import numpy as np
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Perform basic operations
print("Array:", arr)
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))

Array: [1 2 3 4 5]
Mean: 3.0
Sum: 15


## What is array in numpy?

In NumPy, an array is a special data structure called an ndarray (N-dimensional array). It is the core object of NumPy and is used to store collections of elements (numbers, strings, or other data types) in a grid-like structure with fixed size and data type.

### Characteristics of a NumPy Array:
### 1. Homogeneous:
- All elements in a NumPy array must be of the same data type (e.g., all integers, all floats).
### 2. N-Dimensional:
- Arrays can be 1D (vector), 2D (matrix), or higher dimensions (tensor).
### 3. Indexable & Slicable:
- You can access and slice data just like Python lists, but with more powerful features.
### 4. Efficient & Fast:
- Stored in continuous memory blocks, making operations faster than Python lists.
### 5. Supports Vectorized Operations:
- You can perform element-wise arithmetic without loops.

### Example: Creating Arrays in NumPy:

In [3]:
import numpy as np

# 1D Array (like a list)
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# 2D Array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)

# 3D Array (tensor)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", arr3)


1D Array: [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### NOTE: 
- A NumPy array is a multi-dimensional, homogeneous data structure that is more efficient and powerful than Python lists for numerical computations.

## Usage of 1D, 2D and 3D arrays in Numpy

NumPy arrays can be 1D, 2D, or 3D (and higher), and each has its own use cases depending on the type of data we are working with.

### 1D Array (Vector):
- What it is: A simple list-like structure, one row of elements.
- Use case: Useful for linear data such as sequences, signals, feature vectors in machine learning, or storing simple datasets.
- Use case examples:
  - Student marks list [85, 90, 78, 92]
  - Prices of products [100, 200, 150]
  - ML input features for one observation [height, weight, age]
### 2D Array (Matrix):
- What it is: Data arranged in rows and columns (like a table).
- Use case: Used for matrices in linear algebra, images (grayscale), or datasets where you have rows = observations and columns = features.
- Use case examples:
  - Student marks table
### 3D Array (Tensor):
- What it is: Data arranged in multiple 2D matrices stacked together (like a cube).
- Use case: Used in scientific computing, image processing (RGB images), video frames, deep learning (tensors).
- Use case examples:
  - RGB Images → shape (height, width, 3)
  - Videos → shape (frames, height, width, channels)
  - Deep Learning → input data tensors (batch_size, features, time_steps)
### Summary:
- 1D Array: Linear data → vectors, lists, sequences.
- 2D Array: Tabular/matrix data → datasets, images, matrices.
- 3D Array: Multi-layer data → images (RGB), videos, tensors for ML/DL.



In [4]:
# creating numpy arrays
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [5]:
print("1D Array:", a)
print("2D Array:\n", b)
print("3D Array:\n", c)


1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
a.shape


(3,)

### Interpretation:
- This means the array has 1 dimension (it’s a 1D array).
- That single dimension has 3 elements.
- The comma ( , ) indicates it is a tuple describing dimensions.
- So (3,) = "One row with 3 elements" (like a vector).

In [8]:
b.shape

(2, 3)

### Interpretation:
- 2 → Number of rows
- 3 → Number of columns
- Total elements = 2 × 3 = 6

In [9]:
c.shape

(2, 2, 2)

### Interpretation:
- 3D array
- 2 matrices
- Each matrix has 2 rows and 2 columns
- Total elements = 2 × 2 × 2 = 8