# Author Info
---
Name: **Ejaz-ur-Rehman**\
Business Unit Head | Data Analyst\
MBA (Accounting & Finance), MS (Finance)\
Crystal Tech (Project of MUZHAB Group)\
Karachi, Pakistan

![Date](https://img.shields.io/badge/Date-04--September--2025-green?logo=google-calendar)
[![Email](https://img.shields.io/badge/Email-ijazfinance%40gmail.com-blue?logo=gmail)](mailto:ijazfinance@gmail.com)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Ejaz--ur--Rehman-blue?logo=linkedin)](https://www.linkedin.com/in/ejaz-ur-rehman/)
[![GitHub](https://img.shields.io/badge/GitHub-ejazurrehman-black?logo=github)](https://github.com/ejazurrehman)

# What is Linear Algebra?
---

Linear Algebra is a branch of mathematics that deals with vectors, matrices, and linear transformations.
It allows us to represent, manipulate, and solve problems involving large amounts of data.

Instead of dealing with single numbers (scalars), linear algebra works with:
- Scalars → single values
- Vectors → ordered list of numbers (1D)
- Matrices → 2D arrays of numbers
- Tensors → n-dimensional arrays (generalization of matrices)

## Why is Linear Algebra Important in Data Science?
---

In Data Science and ML, data is often represented as matrices & vectors:
### 1. Data Representation
- A dataset with m samples and n features is an m×n matrix.
### 2. Feature Transformation
- Scaling, rotation, and dimensionality reduction (PCA, SVD).
### 3. Machine Learning Models
- Linear regression: Y=X⋅β
- Neural networks use matrix multiplications at each layer.
### 4. Optimization
- Gradients, eigenvalues, eigenvectors.
### 5. Similarity Measures
- Dot product, cosine similarity in NLP & recommender systems.

## Key Linear Algebra Operations in Data Science
---

### 1. Representing a Dataset as a Matrix
- A dataset is usually a matrix X, where rows = samples and columns = features.

In [1]:
import numpy as np

# Dataset: 3 samples, 2 features
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print("Dataset (Matrix X):\n", X)


Dataset (Matrix X):
 [[1 2]
 [3 4]
 [5 6]]


**NOTE:** Each row = one observation, each column = one feature.

### 2. Dot Product (Similarity)
- In ML, dot products measure similarity.
- For vectors a=[1,2], b=[3,4]:
- a⋅b=(1)(3)+(2)(4)=11

In [2]:
a = np.array([1, 2])
b = np.array([3, 4])
dot = np.dot(a, b)
print("Dot Product:", dot)


Dot Product: 11


### 3. Matrix Multiplication (Linear Regression)
- Linear regression formula:
- Y=X⋅β
- Where:
  - X = input features (matrix)
  - β = coefficients (vector)
  - Y = predictions (vector)

In [3]:
# Features matrix (size, bedrooms)
X = np.array([[1000, 2],
              [1500, 3],
              [2000, 4]])

# Coefficients (price per sqft=200, price per bedroom=5000)
beta = np.array([200, 5000])

# Predictions
Y = X.dot(beta) + 10000   # adding bias (intercept)
print("Predicted Prices:", Y)


Predicted Prices: [220000 325000 430000]


### 4. Eigenvalues & Eigenvectors (PCA)
- Principal Component Analysis (PCA) uses eigenvalues/eigenvectors to reduce dimensionality.

In [4]:
from numpy.linalg import eig

# Covariance matrix
A = np.array([[2, 0],
              [0, 1]])

values, vectors = eig(A)
print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)


Eigenvalues: [2. 1.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


**NOTE:** Eigenvalues show importance of directions (variance), eigenvectors show directions (components).

### 5. Singular Value Decomposition (SVD)
- SVD is widely used in recommender systems (Netflix, Spotify).

In [5]:
from numpy.linalg import svd

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

U, S, Vt = svd(A)
print("U:\n", U)
print("S:", S)
print("Vt:\n", Vt)


U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S: [9.52551809 0.51430058]
Vt:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
